language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install -e pipenv --upgrade"
  - "pipenv install --dev --skip-lock"

# command to run tests
script:
  - pipenv run pytest tests